services:

  api-usuarios:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apiusuarios_app
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bd_api_usuarios
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres
    networks:
      - apiusuarios-network

  postgres:
    image: postgres:16
    container_name: postgres_bd_api_usuarios
    restart: always
    environment:
      POSTGRES_DB: bd_api_usuarios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - apiusuarios-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_bd_api_usuarios
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - apiusuarios-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  apiusuarios-network:
    driver: bridge