services:

  postgres:
    image: postgres:16
    container_name: postgres_bd_api_usuarios
    restart: always
    environment:
      POSTGRES_DB: bd_api_usuarios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede_api

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_bd_api_usuarios
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - rede_api
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  rede_api:
    driver: bridge