spring.application.name=api_usuario

 server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5435/bd_api_usuarios
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cors.enabled=http://localhost:4200

jwt.secret=537fb3d6-1192-425e-8142-1e8f4201944e
jwt.expiration=3600000
